config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:new, :index, :create]

end
#
# Prefix Verb   URI Pattern                   Controller#Action

#  users POST   /users(.:format)              users#create
# new_user GET    /users/new(.:format)          users#new


# new_session GET    /session/new(.:format)        sessions#new
# session DELETE /session(.:format)            sessions#destroy
#        POST   /session(.:format)            sessions#create


#   subs GET    /subs(.:format)               subs#index
#        POST   /subs(.:format)               subs#create
# new_sub GET    /subs/new(.:format)           subs#new
# edit_sub GET    /subs/:id/edit(.:format)      subs#edit
#    sub GET    /subs/:id(.:format)           subs#show
#        PATCH  /subs/:id(.:format)           subs#update
#        PUT    /subs/:id(.:format)           subs#update


# sub_posts POST   /subs/:sub_id/posts(.:format) posts#create
# new_sub_post GET    /subs/:sub_id/posts/new(.:format) posts#new
# edit_post GET    /posts/:id/edit(.:format)     posts#edit
#   post GET    /posts/:id(.:format)          posts#show
#        PATCH  /posts/:id(.:format)          posts#update
#        PUT    /posts/:id(.:format)          posts#update
#        DELETE /posts/:id(.:format)          posts#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :sub

  belongs_to :author,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :User

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true, uniqueness: true
  validates :moderator_id, presence: true

  belongs_to :moderator,
  primary_key: :id,
  foreign_key: :moderator_id,
  class_name: :User

  has_many :posts,
  primary_key: :id,
  foreign_key: :sub_id,
  class_name: :Post

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :moderated_subs,
  class_name: :Sub,
  primary_key: :id,
  foreign_key: :moderator_id

  has_many :posts,
  class_name: :Post,
  primary_key: :id,
  foreign_key: :author_id


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in, only: [:create, :new, :destroy]
  before_action :require_author, only: [:edit, :update, :destroy]

  def new
    @sub = Sub.find(params[:sub_id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.sub_id = params[:sub_id]

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end

  def require_author
    @post = Post.find(params[:id])
    redirect_to post_url(@post) unless @post.author_id == current_user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user.nil?
      flash[:errors] = ["Username or Password invalid!"]
      render :new
    else
      login!(@user)
      redirect_to subs_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, only: [:edit, :update]
  before_action :require_logged_in, except: [:show, :index]

  def new

  end

  def show
    @sub = Sub.find(params[:id])
  end

  def index
    @subs = Sub.all
  end

  def edit
    render :edit
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub.id)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def require_moderator
    @sub = Sub.find(params[:id])
    unless current_user.id == @sub.moderator_id
      redirect_to sub_url(params[:id])
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def authentication
    '<input type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">'.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <p>Welcome, <%= current_user.username %></p>
        <%= button_to "Sign Out", session_url, method: :delete %>
      <% else %>
        <%= button_to "Sign In", new_session_url, method: :get %>
        <%= button_to "Sign Up", new_user_url, method: :get %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h1><%= page_type %></h1>

<form action="<%= form_route %>" method="post">
  <%= authentication %>

  <% if page_type == "Edit Post" %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label>
    Title
    <input type="text"
           name="post[title]"
           value="<%= @post.title if @post %>">
  </label>

  <label>
    URL
    <input type="text"
           name="post[password]"
           value="<%= @post.url if @post %>">
  </label>
    Content
    <textarea name="post[content]" rows="8" cols="80"><%= @post.content if @post %></textarea>
  </label>

  <input type="submit" name="" value="<%= page_type %>">
</form>

app/views/posts/edit.html.erb
<%= render "form", page_type: "Edit Post", form_route: post_url(@post) %>

app/views/posts/new.html.erb
<%= render "form", page_type: "New Post", form_route: sub_posts_url(@sub.id) %>

app/views/posts/show.html.erb
<ul>
  <li> Author:<%= @post.author.username %> </li>
  <li> Title:<%= @post.title %> </li>
  <% if @post.url %>
    <li> URL:<%= @post.url %> </li>
  <% end %>
  <% if @post.content %>
    <li> Content:<%= @post.content %> </li>
  <% end %>
</ul>

<%= button_to "Back to Sub", sub_url(@post.sub.id), method: :get %>

app/views/subs/_form.html.erb
<h1><%= page_type %></h1>

<form action="<%= form_type %>" method="post">
  <%= authentication %>

  <% if page_type == "Edit Sub" %>
    <input type="hidden" name="_method" value="PATCH">
  <% end  %>

  <label>Title:
    <input type="text" name="sub[title]" value="<%= @sub.title if @sub %>">
  </label>
  <label>Description:
    <textarea name="sub[description]" rows="8" cols="80"><%= @sub.description if @sub %></textarea>
  </label>

  <input type="submit" name="" value="<%= page_type %>">
</form>

app/views/subs/edit.html.erb
<%= render 'form', form_type: sub_url(@sub.id), page_type: "Edit Sub" %>

app/views/subs/index.html.erb
<ul>

<% @subs.each do |s| %>
  <li> <%= link_to s.title, sub_url(s) %> </li>
<% end %>

</ul>

<%= button_to "Create a new Sub!", new_sub_url, method: :get %>

app/views/subs/new.html.erb
<%= render 'form', form_type: "/subs", page_type: "Create Sub" %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h2>Moderated by: <%= @sub.moderator.username %></h2>
<p><%= @sub.description %></p>

<% if @sub.moderator_id == current_user.id %>
  <%= button_to "Edit Sub", edit_sub_url(@sub), method: :get %>
<% end %>

<%= button_to "Make Post", new_sub_post_url(@sub), method: :get %>

<article>
  <ul>
    <% @sub.posts.each do |post| %>
      <li><%= link_to "#{post.title}", post_url(post.id) %></li>
    <% end %>
  </ul>
</article>

<%= button_to "Back to Main", subs_url, method: :get %>

app/views/users/_user_form.html.erb
<h1><%= page_type %></h1>

<form action="<%= form_route %>" method="post">
  <%= authentication %>

  <label>
    Username
    <input type="text"
           name="user[username]"
           value="<%= @user.username if @user %>">
  </label>

  <label>
    Password
    <input type="password"
           name="user[password]"
           value="">
  </label>

  <input type="submit" name="" value="<%= page_type %>">
</form>

app/views/users/new.html.erb
<%= render 'user_form',
    page_type: "Sign Up",
    form_route: users_url %>